services:
  db:
    image: postgres:15
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: dockerAdmin123
      POSTGRES_DB: course_spring_boot
    ports:
      - 5432:5432
    networks:
      - api-network

  app_java:
    image: benjamimthiago/rest-with-spring-boot-erudio
    restart: always
    build: ./app
    working_dir: /app
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/course_spring_boot
      SPRING.DATASOURCE.USERNAME: docker
      SPRING.DATASOURCE.PASSWORD: dockerAdmin123
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - api-network
      
networks:
  api-network:
    driver: bridge

